# Generated by Django 4.2.4 on 2023-08-19 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order_app', '0011_extendsupportplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.BooleanField(default=False, verbose_name='آماده سازی قالب سایت')),
                ('account_system', models.BooleanField(default=False, verbose_name='ایجاد بخش حساب کاربری')),
                ('database', models.BooleanField(default=False, verbose_name='ایجاد دیتابیس سایت')),
                ('back_end', models.BooleanField(default=False, verbose_name='نوشتن کد بخش پردازش سایت')),
                ('customize_admin_panel', models.BooleanField(default=False, verbose_name='ایجاد و شخصی سازی پنل ادمین')),
                ('test', models.BooleanField(default=False, verbose_name='تست عملکرد وبسایت')),
                ('deploy', models.BooleanField(default=False, verbose_name='انتقال پروژه به هاست')),
                ('finished', models.BooleanField(default=False, verbose_name='تحویل وبسایت به شما')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='order_app.order', verbose_name='سفارش')),
            ],
        ),
    ]
