# Generated by Django 4.2.4 on 2023-08-19 05:29

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='checklist',
            name='updated_at',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, null=True),
        ),
    ]
