# Generated by Django 4.2.4 on 2023-08-15 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0002_delete_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='plan_category',
            field=models.CharField(default='فروشگاهی', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='plan_type',
            field=models.CharField(default='نقره ای', max_length=100),
        ),
    ]
