# Generated by Django 4.2.4 on 2023-08-15 06:56

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0003_order_plan_category_order_plan_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pay_at',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True),
        ),
    ]
