# Generated by Django 4.2.4 on 2023-08-15 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0004_order_pay_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='preparation_template',
        ),
        migrations.RemoveField(
            model_name='order',
            name='preparing',
        ),
        migrations.RemoveField(
            model_name='order',
            name='seventy_percent_ready',
        ),
        migrations.RemoveField(
            model_name='order',
            name='thirty_five_percent_ready',
        ),
        migrations.AddField(
            model_name='order',
            name='preparation_percentage',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
