# Generated by Django 4.2.4 on 2023-08-17 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_app', '0003_remove_price_category_price_category'),
        ('order_app', '0007_support'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('ability', models.ManyToManyField(to='price_app.ability')),
            ],
        ),
    ]
