# Generated by Django 4.2.4 on 2023-08-17 10:38

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0008_supportplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='expiration_date',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True),
        ),
    ]
