# Generated by Django 4.2.4 on 2023-08-19 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0010_alter_support_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtendSupportPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
