# Generated by Django 4.2.4 on 2023-08-20 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0011_extendsupportplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='support',
            name='site_panel_address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='support',
            name='site_panel_password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='support',
            name='site_panel_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
