# Generated by Django 4.2.4 on 2023-08-20 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0012_support_site_panel_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='support',
            name='applied_discount_code',
        ),
        migrations.RemoveField(
            model_name='support',
            name='is_discount_applied',
        ),
    ]
