# Generated by Django 4.2.4 on 2023-08-21 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0003_announcement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='user',
        ),
    ]
