# Generated by Django 4.2.4 on 2023-08-15 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_app', '0002_remove_price_category_price_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='category',
        ),
        migrations.AddField(
            model_name='price',
            name='category',
            field=models.ManyToManyField(to='price_app.pricecategory'),
        ),
    ]
