# Generated by Django 4.2.4 on 2023-08-14 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact_us',
            new_name='ContactUs',
        ),
    ]
