# Generated by Django 4.2.4 on 2023-08-14 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us_app', '0003_alter_contactus_email_alter_contactus_message_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='contactus',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نام خانوادگی'),
        ),
    ]
