# Generated by Django 4.2.4 on 2023-08-14 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us_app', '0004_rename_name_contactus_first_name_contactus_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=11)),
                ('phone_2', models.CharField(blank=True, max_length=11, null=True)),
                ('phone_3', models.CharField(blank=True, max_length=11, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('email_2', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
