# Generated by Django 4.2.4 on 2023-08-15 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us_app', '0005_companyinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
