# Generated by Django 4.2.4 on 2023-08-11 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, verbose_name='آدرس ایمیل')),
                ('fullname', models.CharField(max_length=80, verbose_name='نام و نام خانوادگی')),
                ('phone', models.IntegerField(max_length=11, unique=True, verbose_name='تلفن همراه')),
                ('image', models.ImageField(blank=True, null=True, upload_to='user/images', verbose_name='عکس پروفایل')),
                ('address', models.CharField(max_length=300, verbose_name='آدرس')),
                ('sex', models.CharField(choices=[('مرد', 'مرد'), ('زن', 'زن')], max_length=20, verbose_name='جنسیت')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='زمان عضویت')),
                ('is_active', models.BooleanField(default=False, verbose_name='وضعیت کاربر')),
                ('is_admin', models.BooleanField(default=False, verbose_name='ادمین')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربرها',
            },
        ),
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=11, verbose_name='تلفن همراه')),
                ('code', models.SmallIntegerField(verbose_name='کد اعتبار سنجی')),
                ('fullname', models.CharField(max_length=80, verbose_name='نام و نام خانوادگی')),
                ('email', models.EmailField(max_length=255, verbose_name='آدرس ایمیل')),
                ('password1', models.CharField(max_length=50, verbose_name='گذرواژه')),
                ('password2', models.CharField(max_length=50, verbose_name='تکرار گذرواژه')),
                ('expiration_date', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ انقضا')),
            ],
            options={
                'verbose_name': 'اعتبار سنجی',
                'verbose_name_plural': 'اعتبار سنجی ها',
            },
        ),
        migrations.CreateModel(
            name='Ban',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
