# Generated by Django 4.2.4 on 2023-08-13 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0004_user_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(blank=True, choices=[('مرد', 'مرد'), ('زن', 'زن')], max_length=20, null=True, verbose_name='جنسیت'),
        ),
    ]
