# Generated by Django 4.2.4 on 2023-08-14 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0005_alter_user_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_buy',
            field=models.BooleanField(default=False),
        ),
    ]
