# Generated by Django 4.2.4 on 2023-08-16 04:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0007_alter_user_is_buy'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLoginInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os', models.CharField(max_length=50)),
                ('browser', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=50)),
                ('ip', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='last_logins', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
