# Generated by Django 4.2.4 on 2023-08-16 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0009_remove_otp_email_remove_otp_fullname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_two_step',
            field=models.BooleanField(default=False, verbose_name='ورود دو مرحله ای'),
        ),
    ]
