# Generated by Django 4.2.4 on 2023-08-17 05:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0010_user_is_two_step'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLoginCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='count', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
