# Generated by Django 4.2.4 on 2023-08-14 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_app', '0002_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='teammember',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='about_app.teamcategory'),
        ),
    ]
